export type Movie = {
  id: string;
  title: string;
  author: string;
  genre: string[];
  rating: number;
  reviewCount: number;
  description: string;
  affiliateUrl: string;
  imageUrl?: string;
  rank?: number;
};

export const movies: Movie[] = [
  {
    id: "1",
    title: "失恋して兄貴に慰められた話",
    author: "",
    genre: ["BL", "あまあま", "女性向け"],
    rating: 5.0,
    reviewCount: 3,
    description: "失恋直後に兄貴に慰められて……。ラブラブで甘い近親BL同人誌。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_743574%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_743574/d_743574pl.jpg",
    rank: 1,
  },
  {
    id: "2",
    title: "高慢王子を無様に理解らせ愛玩堕とし【合本版】",
    author: "",
    genre: ["BL", "わからせ", "異世界転生"],
    rating: 4.5,
    reviewCount: 4,
    description: "高慢な王子がわからせられ堕ちていく異世界BL。拘束・連続絶頂の濃厚展開。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_755406%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_755406/d_755406pl.jpg",
    rank: 2,
  },
  {
    id: "3",
    title: "三兄弟でなかよしえっち次男受け",
    author: "",
    genre: ["BL", "あまあま", "女性向け"],
    rating: 5.0,
    reviewCount: 3,
    description: "三兄弟の甘くてHな同人BL。次男受けのラブラブえっちを描いた話。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_556317%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_556317/d_556317pl.jpg",
    rank: 3,
  },
  {
    id: "4",
    title: "大穢-完全版-",
    author: "",
    genre: ["BL", "ホラー", "ミステリー"],
    rating: 4.7,
    reviewCount: 25,
    description: "スーツ×ホラー×BLのミステリアスな同人作品。完全版で全編収録。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_426055%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/game/d_426055/d_426055pl.jpg",
    rank: 4,
  },
  {
    id: "5",
    title: "豊穣の島-孕み袋となる漁師-",
    author: "",
    genre: ["BL", "ファンタジー", "異種姦"],
    rating: 0,
    reviewCount: 0,
    description: "褐色の漁師が島の秘密に巻き込まれるダークファンタジーBL同人誌。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_460182%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_460182/d_460182pl.jpg",
    rank: 5,
  },
  {
    id: "6",
    title: "ガガイルとギルレムナ",
    author: "",
    genre: ["BL", "ファンタジー", "エルフ"],
    rating: 5.0,
    reviewCount: 3,
    description: "エルフ×魔法使いのファンタジーBL。青姦シーンも収録した幻想的な同人誌。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_748548%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_748548/d_748548pl.jpg",
    rank: 6,
  },
  {
    id: "7",
    title: "性奴隷ヤンキーくん陵辱チャンネル",
    author: "",
    genre: ["BL", "拘束", "女性向け"],
    rating: 4.7,
    reviewCount: 3,
    description: "ヤンキーが拘束・調教されていく濃厚BL同人誌。連続絶頂の描写が刺さる一作。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_755865%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_755865/d_755865pl.jpg",
    rank: 7,
  },
  {
    id: "8",
    title: "先生を躾けようなんて僕が間違ってました",
    author: "",
    genre: ["BL", "わからせ", "ノンケ"],
    rating: 0,
    reviewCount: 0,
    description: "先生をわからせようとした生徒が逆に……？ノンケ×わからせ逆転BL同人誌。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_367181%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_367181/d_367181pl.jpg",
    rank: 8,
  },
  {
    id: "9",
    title: "ベアーソング",
    author: "",
    genre: ["BL", "筋肉", "ゲイ"],
    rating: 4.6,
    reviewCount: 7,
    description: "筋肉×ゲイBLの同人誌。コミケ95発行作品で、骨太な男同士の絡みを描く。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_147216%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_147216/d_147216pl.jpg",
    rank: 9,
  },
  {
    id: "10",
    title: "むちむち人妻♂お兄さん、水泳教室でNTRれる。",
    author: "",
    genre: ["BL", "NTR", "年下攻め"],
    rating: 0,
    reviewCount: 0,
    description: "むちむちな人妻♂お兄さんが水泳教室で年下に寝取られる背徳BL同人誌。",
    affiliateUrl: "https://al.fanza.co.jp/?lurl=https%3A%2F%2Flovecul.dmm.co.jp%2Fbl%2F-%2Fdetail%2F%3D%2Fcid%3Dd_779085%2F&af_id=fanzame-001&ch=search_link&ch_id=package",
    imageUrl: "https://doujin-assets.dmm.co.jp/digital/comic/d_779085/d_779085pl.jpg",
    rank: 10,
  },
];
